repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
        args: ['--maxkb 100']
    -   id: check-json
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: debug-statements
    -   id: mixed-line-ending
-   repo: https://github.com/pycqa/isort
    rev: '5.12.0'
    hooks:
    -   id: isort
        name: isort
        files: "\\.(py)$"
        args:
        - --profile=black
-   repo: https://github.com/psf/black
    rev: '22.3.0'
    hooks:
    -   id: black
        args:
        - --line-length=120
        - --preview
-   repo: https://github.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
    -   id: flake8
        args:
        - --max-line-length=120
        - --ignore=E203,W503
        - --per-file-ignores=gridnerf/train/modules/models/__init__.py:F401
-   repo: https://github.com/PyCQA/pylint/
    rev: 'v2.15.0'
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
            [
                '--rcfile=.pylintrc',
                '--disable=C0103,C0114,C0415,W0212,W0235,W0238'
            ]
